<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bouton_deconnexion</name>
   <tag></tag>
   <elementGuidId>315fb842-2551-41af-bfea-5824d7d94d42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lnkDeconnexion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='lnkDeconnexion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Déconnexion&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>20575cc8-c6c1-411f-8f6b-e93830e50818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lnkDeconnexion</value>
      <webElementGuid>0bf8ab46-9d39-429b-b6d6-c6d3f93c4e16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-dark pull-right</value>
      <webElementGuid>62e776e6-ebac-4695-818e-273d0ecab0ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/logout</value>
      <webElementGuid>a1eb0f03-1d8c-4585-9dca-eeef2cda675b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Déconnexion</value>
      <webElementGuid>672308bd-5db7-4257-bff9-95f246b294ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lnkDeconnexion&quot;)</value>
      <webElementGuid>c245f5b5-d1c4-4faf-b59c-cedefdd1bbc5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='lnkDeconnexion']</value>
      <webElementGuid>19035b67-c914-4b3e-9882-25d6b645682a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarNavDropdown']/div[3]/a</value>
      <webElementGuid>b3e7ffa2-ffaa-4445-bba2-be4400874445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Déconnexion')]</value>
      <webElementGuid>6fb82867-6ad7-4085-9848-91d6c6da5d59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='rcd'])[1]/following::a[1]</value>
      <webElementGuid>eacc3e85-9332-465b-b6c8-d8fd9ca24070</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rapport de production'])[1]/following::a[1]</value>
      <webElementGuid>8c1b331c-7566-451a-82e4-5675ea305055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Votre menu :'])[1]/preceding::a[1]</value>
      <webElementGuid>af5da37e-6692-4db8-9879-ec7d3dab9461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Déconnexion']/parent::*</value>
      <webElementGuid>0a216cff-2c6f-4f62-a600-b58d358eb9d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/logout')]</value>
      <webElementGuid>b0d91127-abdc-40f2-a599-44f93156bc00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>6086f176-ec7f-447d-8ff9-ef3b7106faa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'lnkDeconnexion' and @href = '/logout' and (text() = 'Déconnexion' or . = 'Déconnexion')]</value>
      <webElementGuid>44836e2d-7eda-46fe-b06e-cb06ca5edcbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
