<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bouton_creer_contrat</name>
   <tag></tag>
   <elementGuidId>7da86d89-641f-4d92-947b-5f1003d8a2f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='lnkCreerContrat'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.form-group > #lnkCreerContrat</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Créer contrat&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bcf2cc93-b050-4c76-8ef9-312ef2a3304b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lnkCreerContrat</value>
      <webElementGuid>72c7810b-2f09-4163-9fc0-19c6161c2a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/credit/contract</value>
      <webElementGuid>70503f55-c577-42cd-be4c-2468690da74d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-light pull-right</value>
      <webElementGuid>51b059df-2962-4446-89cf-e9c874300b0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                         Créer contrat
                    </value>
      <webElementGuid>ec0ec3cb-cd6b-4562-a9ea-f2925c855253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contract&quot;)/form[1]/fieldset[@class=&quot;scheduler-border&quot;]/div[@class=&quot;form-group&quot;]/a[@id=&quot;lnkCreerContrat&quot;]</value>
      <webElementGuid>4aa146e8-2ac9-4ba5-984d-7c83bea9a0a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id='lnkCreerContrat'])[2]</value>
      <webElementGuid>2d456625-e56f-43fe-9382-ba84745747b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contract']/form/fieldset/div/a[2]</value>
      <webElementGuid>3307a06d-b26a-443c-a13c-3595dec853c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Annuler'])[1]/following::a[1]</value>
      <webElementGuid>83b24534-2463-4676-9ec9-30eb70e21b5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Montant achat'])[1]/preceding::a[1]</value>
      <webElementGuid>cf3a4cfc-f636-4fc6-9f04-053aa44ce4cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Créer contrat']/parent::*</value>
      <webElementGuid>2f4fc3c9-5f3f-4077-b749-865e56bf8637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/credit/contract')]</value>
      <webElementGuid>6d5b35c9-f4f0-46e4-9d91-03508ae2fec8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>378d5377-caf7-4284-8723-66b11f4432ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'lnkCreerContrat' and @href = '/credit/contract' and (text() = '
                         Créer contrat
                    ' or . = '
                         Créer contrat
                    ')]</value>
      <webElementGuid>0c85a45b-9e58-4dfe-a3ed-238a0843fc37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
