<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>message_bienvenue</name>
   <tag></tag>
   <elementGuidId>b877523e-8d87-4ced-9ffc-36ce60e0cc46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='page-top']/div/h4</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Bienvenue sur l'application Crédit Auto&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>0f7fba20-2fd1-4e62-a0c3-79adf8fb9e9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bienvenue sur l'application Crédit Auto</value>
      <webElementGuid>eb29e085-be56-4cad-8ad3-4581df2866c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-top&quot;)/div[@class=&quot;jumbotron bg-transparent text-center&quot;]/h4[1]</value>
      <webElementGuid>77ab89b9-180b-4e26-a346-9a46aef34df9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='page-top']/div/h4</value>
      <webElementGuid>f93d4226-1c1d-40d7-ad68-d39c0602e5eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Déconnexion'])[1]/following::h4[1]</value>
      <webElementGuid>74cd372a-5dbc-4cf8-842e-4b7ddc906f9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='gcd'])[1]/following::h4[1]</value>
      <webElementGuid>56657b27-14f4-4c48-88d3-ab7ab8fa39ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Votre menu :'])[1]/preceding::h4[1]</value>
      <webElementGuid>9c56e276-eca6-45e5-9e31-b81e25684366</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='gcd'])[2]/preceding::h4[1]</value>
      <webElementGuid>f80c7853-84df-4b1c-8db8-8cc4c392e93d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>aa65469b-0531-48cc-8361-30d19a6cfbe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = concat(&quot;Bienvenue sur l&quot; , &quot;'&quot; , &quot;application Crédit Auto&quot;) or . = concat(&quot;Bienvenue sur l&quot; , &quot;'&quot; , &quot;application Crédit Auto&quot;))]</value>
      <webElementGuid>40ea9534-bb6d-4b70-85f2-2667ce0aa706</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
